### PR TITLE
Initialize database

### PR DESCRIPTION
**Pull request by Alos444**
Changed the sql file

### CODE REVIEW

**Comment by Alos444** [comment]
Merging changes

**Review by mel-muhina — CHANGES_REQUESTED** [review]
Removes ID values that aren't automatic.

**Review by Nas-1998 — DISMISSED** [review]
Remove Id values set to primary keys and foreign keys

**Comment by Alos444** [comment]
sql changes

**Comment by Alos444** [comment]
Corrected sql

**Review by pedroavpereira — APPROVED** [review]
Tested on local machine, all working!

**Review by mel-muhina — APPROVED** [review]
Approved

**Pull request merged**
